name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - name: Install IKONO package dependencies and build 🔧
        run: npm ci && npm run build:web
      - name: Install IKONO/react package dependencies
        run: cd react && npm ci && cd ..
      - name: Build IKONO/react package 🔧
        run: npm run build:react_library
      - name: Publish IKONO package to NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish IKONO/react package to NPM 📦
        run: cd react & npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
