name: Release
on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Display version
        run: |
          VERSION=${{ github.event.release.tag_name}}
          echo '${{ VERSION#v }}'

      - name: Update package.json version
        run: |
          npm version ${{ github.event.release.tag_name }}
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "[Automated Commit] Update version to ${{ github.event.release.tag_name }}"
          git push
      - name: Update react package.json version
        run: |
          cd react
          npm version ${{ github.event.release.tag_name }}
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "[Automated Commit] Update version to ${{ github.event.release.tag_name }}"
          git push