name: Release
on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Display version
        id: get_tag
        run: |
          VERSION=v1.10.0
          echo ::set-output name=VERSION::$(echo $VERSION | cut -c 2-)
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git submodule update --init --recursive
      - name: Update react package.json version
        run: |
          cd react
          echo "${{ steps.get_tag.outputs.VERSION }}"
          npm version "${{ steps.get_tag.outputs.VERSION }}" --git-tag-version false
          # git push origin HEAD:main
      - name: Save changes to git
        run: |
          cd react
          git add .
          git commit -m "[Automated Commit] Update version to ${{ steps.get_tag.outputs.VERSION }}"
          # git push origin HEAD:main
      - name: Update package.json version
        run: |
          npm version "${{ steps.get_tag.outputs.VERSION }}" --git-tag-version false
      - name: Save changes to git
        run: |
          git add .
          git commit -m "[Automated Commit] Update version to ${{ steps.get_tag.outputs.VERSION }}"
          # git push origin HEAD:main

      